const Book = require('../models/Book')
const User = require('../models/User')
const data = [
    {
        "id": 16470,
        "content_type": 1,
        "platform": 1,
        "title": "Học khôn ngoan để dẫn đầu",
        "slug": "Hoc khon ngoan de dan dau",
        "rate": "5.0",
        "total_rate": 370,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16470.jpg?v=1&w=200&h=292",
        "author": "Olav Schewe",
        "detailLink": "https://ebook.waka.vn/hoc-khon-ngoan-de-dan-dau-b5XDWW.html"
    },
    {
        "id": 19286,
        "content_type": 1,
        "platform": 1,
        "title": "Tiếng Việt - Văn Việt - Người Việt",
        "slug": "Tieng Viet - Van Viet - Nguoi Viet",
        "rate": "5.0",
        "total_rate": 101,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/19286.jpg?v=1&w=200&h=292",
        "author": "Cao Xuân Hạo",
        "detailLink": "https://ebook.waka.vn/tieng-viet-van-viet-nguoi-viet-brqgwW.html"
    },
    {
        "id": 22977,
        "content_type": 1,
        "platform": 1,
        "title": "Thất nhân tâm",
        "slug": "That nhan tam",
        "rate": "4.9",
        "total_rate": 103,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22977.jpg?v=1&w=200&h=292",
        "author": "Hoàng Xuân Việt",
        "detailLink": "https://ebook.waka.vn/that-nhan-tam-bzrxAW.html"
    },
    {
        "id": 21896,
        "content_type": 1,
        "platform": 1,
        "title": "Thu hút thiện cảm, tạo dựng lòng tin",
        "slug": "Thu hut thien cam, tao dung long tin",
        "rate": "4.9",
        "total_rate": 199,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/21896.jpg?v=2&w=200&h=292",
        "author": "Dale Carnegie",
        "detailLink": "https://ebook.waka.vn/thu-hut-thien-cam-tao-dung-long-tin-blnjMW.html"
    },
    {
        "id": 16115,
        "content_type": 1,
        "platform": 1,
        "title": "Luyện trí nhớ bằng kỹ năng ghi nhớ",
        "slug": "Luyen tri nho bang ky nang ghi nho",
        "rate": "4.9",
        "total_rate": 601,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16115.jpg?v=1&w=200&h=292",
        "author": "1980 Books",
        "detailLink": "https://ebook.waka.vn/luyen-tri-nho-bang-ky-nang-ghi-nho-bo3p6W.html"
    },
    {
        "id": 14351,
        "content_type": 1,
        "platform": 1,
        "title": "Phi lý một cách hợp lý",
        "slug": "Phi ly mot cach hop ly",
        "rate": "4.9",
        "total_rate": 469,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14351.jpg?v=3&w=200&h=292",
        "author": "Dan Ariely",
        "detailLink": "https://ebook.waka.vn/phi-ly-mot-cach-hop-ly-bZ4d4W.html"
    },
    {
        "id": 23745,
        "content_type": 1,
        "platform": 1,
        "title": "Thoát khỏi bẫy cảm xúc hay trò lửa đảo của tâm trí",
        "slug": "Thoat khoi bay cam xuc hay tro lua dao cua tam tri",
        "rate": "4.9",
        "total_rate": 289,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/23745.jpg?v=2&w=200&h=292",
        "author": "Thiện Từ",
        "detailLink": "https://ebook.waka.vn/thoat-khoi-bay-cam-xuc-hay-tro-lua-dao-cua-tam-tri-bpNvWW.html"
    },
    {
        "id": 22904,
        "content_type": 1,
        "platform": 1,
        "title": "Làm mẹ yêu nghề là được (Hoàn hảo cũng được, không hoàn hảo cũng được)",
        "slug": "Lam me yeu nghe la duoc (Hoan hao cung duoc, khong hoan hao cung duoc)",
        "rate": "5.0",
        "total_rate": 65,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22904.jpg?v=1&w=200&h=292",
        "author": "Libby Purves",
        "detailLink": "https://ebook.waka.vn/lam-me-yeu-nghe-la-duoc-hoan-hao-cung-duoc-khong-hoan-hao-cung-duoc-bwxZQW.html"
    },
    {
        "id": 22876,
        "content_type": 1,
        "platform": 1,
        "title": "Đừng bán khi chưa được giá",
        "slug": "Dung ban khi chua duoc gia",
        "rate": "4.9",
        "total_rate": 30,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22876.jpg?v=1&w=200&h=292",
        "author": "John Warrilow",
        "detailLink": "https://ebook.waka.vn/dung-ban-khi-chua-duoc-gia-bW4yaW.html"
    },
    {
        "id": 22794,
        "content_type": 1,
        "platform": 1,
        "title": "Bắn tim - Bí quyết chuẩn teen",
        "slug": "Ban tim - Bi quyet chuan teen",
        "rate": "5.0",
        "total_rate": 22,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22794.jpg?v=1&w=200&h=292",
        "author": "Mr. Biết Tuốt",
        "detailLink": "https://ebook.waka.vn/ban-tim-bi-quyet-chuan-teen-bGNgnW.html"
    },
    {
        "id": 22160,
        "content_type": 1,
        "platform": 1,
        "title": "Vấp, nhưng đừng ngã",
        "slug": "[Tom tat sach] Vap, nhung dung nga",
        "rate": "5.0",
        "total_rate": 12,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22160.jpg?v=1&w=200&h=292",
        "author": "Vũ Thái Hà",
        "detailLink": "https://ebook.waka.vn/tom-tat-sach-vap-nhung-dung-nga-bOYV4W.html"
    },
    {
        "id": 22150,
        "content_type": 1,
        "platform": 1,
        "title": "Từ bỏ thì dễ -  vượt lên chính mình mới khó",
        "slug": "[Tom tat sach] Tu bo thi de -  vuot len chinh minh moi kho",
        "rate": "4.9",
        "total_rate": 143,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/22150.jpg?v=1&w=200&h=292",
        "author": "Ngô Mục Thiên",
        "detailLink": "https://ebook.waka.vn/tom-tat-sach-tu-bo-thi-de-vuot-len-chinh-minh-moi-kho-bGNV3W.html"
    },
    {
        "id": 21914,
        "content_type": 1,
        "platform": 1,
        "title": "Đủ nắng thì hoa nở",
        "slug": "Du nang thi hoa no",
        "rate": "4.9",
        "total_rate": 192,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/21914.jpg?v=1&w=200&h=292",
        "author": "Ba Gàn",
        "detailLink": "https://ebook.waka.vn/du-nang-thi-hoa-no-bKndpW.html"
    },
    {
        "id": 21383,
        "content_type": 1,
        "platform": 1,
        "title": "Giải quyết xung đột trong cuộc sống",
        "slug": "Giai quyet xung dot trong cuoc song",
        "rate": "4.9",
        "total_rate": 160,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/21383.jpg?v=1&w=200&h=292",
        "author": "Dale Carnegie",
        "detailLink": "https://ebook.waka.vn/giai-quyet-xung-dot-trong-cuoc-song-bMDEmW.html"
    },
    {
        "id": 21380,
        "content_type": 1,
        "platform": 1,
        "title": "Chuẩn bị để thăng tiến trong sự nghiệp",
        "slug": "Chuan bi de thang tien trong su nghiep",
        "rate": "4.8",
        "total_rate": 135,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/21380.jpg?v=1&w=200&h=292",
        "author": "Dale Carnegie",
        "detailLink": "https://ebook.waka.vn/chuan-bi-de-thang-tien-trong-su-nghiep-b0egwW.html"
    },
    {
        "id": 21083,
        "content_type": 1,
        "platform": 1,
        "title": "Elon Musk - Tesla, SpaceX & Sứ mệnh tìm kiếm ngoài sức tưởng tượng",
        "slug": "[Tom tat sach] Elon Musk - Tesla, SpaceX _ Su menh tim kiem ngoai suc tuong tuong",
        "rate": "4.9",
        "total_rate": 23,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/21083.jpg?v=1&w=200&h=292",
        "author": "Ashlee Vance",
        "detailLink": "https://ebook.waka.vn/tom-tat-sach-elon-musk-tesla-spacex-su-menh-tim-kiem-ngoai-suc-tuong-tuong-bM1yoW.html"
    },
    {
        "id": 20687,
        "content_type": 1,
        "platform": 1,
        "title": "Mã Vân - Triết lý sống của tôi",
        "slug": "[Tom tat sach] Ma Van - Triet ly song cua toi",
        "rate": "4.9",
        "total_rate": 85,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/20687.jpg?v=2&w=200&h=292",
        "author": "Trương Yến",
        "detailLink": "https://ebook.waka.vn/tom-tat-sach-ma-van-triet-ly-song-cua-toi-bQV0OW.html"
    },
    {
        "id": 19807,
        "content_type": 1,
        "platform": 1,
        "title": "Hạnh phúc không mặc đồng phục",
        "slug": "Hanh phuc khong mac dong phuc",
        "rate": "4.9",
        "total_rate": 77,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/19807.jpg?v=1&w=200&h=292",
        "author": "Tạ Hà Như Bình",
        "detailLink": "https://ebook.waka.vn/hanh-phuc-khong-mac-dong-phuc-bZ774W.html"
    },
    {
        "id": 19709,
        "content_type": 1,
        "platform": 1,
        "title": "Thay đổi hay là chết",
        "slug": "Thay doi hay la chet",
        "rate": "4.9",
        "total_rate": 447,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/19709.jpg?v=1&w=200&h=292",
        "author": "Alexi Panos, Preston Smiles",
        "detailLink": "https://ebook.waka.vn/thay-doi-hay-la-chet-bnd6rW.html"
    },
    {
        "id": 19452,
        "content_type": 1,
        "platform": 1,
        "title": "Nghệ thuật hiểu thấu tâm lý người khác",
        "slug": "Nghe thuat hieu thau tam ly nguoi khac",
        "rate": "4.9",
        "total_rate": 626,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/19452.jpg?v=1&w=200&h=292",
        "author": "Nguyễn Minh Đức, Nguyễn Công Khanh",
        "detailLink": "https://ebook.waka.vn/nghe-thuat-hieu-thau-tam-ly-nguoi-khac-bldaqW.html"
    },
    {
        "id": 19305,
        "content_type": 1,
        "platform": 1,
        "title": "Tâm lý học chuyên sâu - Ý thức và những tầng sâu vô thức",
        "slug": "Tam ly hoc chuyen sau - Y thuc va nhung tang sau vo thuc",
        "rate": "4.9",
        "total_rate": 576,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/19305.jpg?v=1&w=200&h=292",
        "author": "Lưu Hồng Khanh",
        "detailLink": "https://ebook.waka.vn/tam-ly-hoc-chuyen-sau-y-thuc-va-nhung-tang-sau-vo-thuc-bNyXWW.html"
    },
    {
        "id": 17787,
        "content_type": 1,
        "platform": 1,
        "title": "Nhảy việc hay thay đổi chính mình",
        "slug": "Nhay viec hay thay doi chinh minh",
        "rate": "4.9",
        "total_rate": 218,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17787.jpg?v=1&w=200&h=292",
        "author": "Jon Acuff",
        "detailLink": "https://ebook.waka.vn/nhay-viec-hay-thay-doi-chinh-minh-bQy2wW.html"
    },
    {
        "id": 17569,
        "content_type": 1,
        "platform": 1,
        "title": "Khi bạn là CEO - 100 câu hỏi tiêu biểu",
        "slug": "Khi ban la CEO - 100 cau hoi tieu bieu",
        "rate": "4.9",
        "total_rate": 78,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17569.jpg?v=1&w=200&h=292",
        "author": "Võ Văn Thành Nghĩa",
        "detailLink": "https://ebook.waka.vn/khi-ban-la-ceo-100-cau-hoi-tieu-bieu-bmqwjW.html"
    },
    {
        "id": 17480,
        "content_type": 1,
        "platform": 1,
        "title": "Nghệ thuật thuyết phục đỉnh cao",
        "slug": "Nghe thuat thuyet phuc dinh cao",
        "rate": "4.9",
        "total_rate": 140,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17480.jpg?v=1&w=200&h=292",
        "author": "Peter Coughter",
        "detailLink": "https://ebook.waka.vn/nghe-thuat-thuyet-phuc-dinh-cao-b0qgdW.html"
    },
    {
        "id": 17451,
        "content_type": 1,
        "platform": 1,
        "title": "Branding 4.0",
        "slug": "Branding 4_0",
        "rate": "4.9",
        "total_rate": 86,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17451.jpg?v=1&w=200&h=292",
        "author": "Piyachart Isarabhakdee, Philip Kotler",
        "detailLink": "https://ebook.waka.vn/branding-4-0-bZxp5W.html"
    },
    {
        "id": 17409,
        "content_type": 1,
        "platform": 1,
        "title": "Giao tiếp thông minh và tài ứng xử",
        "slug": "Giao tiep thong minh va tai ung xu",
        "rate": "4.9",
        "total_rate": 478,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17409.jpg?v=1&w=200&h=292",
        "author": "Đào Bằng, Khuất Quang Hỉ",
        "detailLink": "https://ebook.waka.vn/giao-tiep-thong-minh-va-tai-ung-xu-bn3NWW.html"
    },
    {
        "id": 17412,
        "content_type": 1,
        "platform": 1,
        "title": "Nguyên tắc vàng của Napoleon Hill",
        "slug": "Nguyen tac vang cua Napoleon Hill",
        "rate": "5.0",
        "total_rate": 80,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17412.jpg?v=1&w=200&h=292",
        "author": "Napoleon Hill",
        "detailLink": "https://ebook.waka.vn/nguyen-tac-vang-cua-napoleon-hill-b1510W.html"
    },
    {
        "id": 17339,
        "content_type": 1,
        "platform": 1,
        "title": "Nghệ thuật nâng cao chất lượng công việc",
        "slug": "Nghe thuat nang cao chat luong cong viec",
        "rate": "4.8",
        "total_rate": 20,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17339.jpg?v=1&w=200&h=292",
        "author": "Subir Chowdhury",
        "detailLink": "https://ebook.waka.vn/nghe-thuat-nang-cao-chat-luong-cong-viec-bMZeVW.html"
    },
    {
        "id": 17285,
        "content_type": 1,
        "platform": 1,
        "title": "Tuổi 20 - Sức hút từ kỹ năng giao tiếp",
        "slug": "Tuoi 20 - Suc hut tu ky nang giao tiep",
        "rate": "4.9",
        "total_rate": 117,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17285.jpg?v=1&w=200&h=292",
        "author": "Kim Thục Lệ",
        "detailLink": "https://ebook.waka.vn/tuoi-20-suc-hut-tu-ky-nang-giao-tiep-bXYQ6W.html"
    },
    {
        "id": 17240,
        "content_type": 1,
        "platform": 1,
        "title": "Điểm Mù",
        "slug": "Diem Mu",
        "rate": "5.0",
        "total_rate": 37,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17240.jpg?v=1&w=200&h=292",
        "author": "Max H. Bazerman & Ann E.Tenbrunsel",
        "detailLink": "https://ebook.waka.vn/diem-mu-beZwmW.html"
    },
    {
        "id": 17256,
        "content_type": 1,
        "platform": 1,
        "title": "Học từ cuộc sống",
        "slug": "Hoc tu cuoc song",
        "rate": "4.9",
        "total_rate": 441,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17256.jpg?v=1&w=200&h=292",
        "author": "Hữu Hưng",
        "detailLink": "https://ebook.waka.vn/hoc-tu-cuoc-song-b15N5W.html"
    },
    {
        "id": 17204,
        "content_type": 1,
        "platform": 1,
        "title": "Nền tảng & ứng dụng của Bản đồ Tư duy",
        "slug": "Nen tang _ ung dung cua Ban do Tu duy",
        "rate": "4.9",
        "total_rate": 48,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17204.jpg?v=1&w=200&h=292",
        "author": "Tony Buzan",
        "detailLink": "https://ebook.waka.vn/nen-tang-ung-dung-cua-ban-do-tu-duy-bwLjRW.html"
    },
    {
        "id": 17115,
        "content_type": 1,
        "platform": 1,
        "title": "V.Putin từ trung tá KGB đến Tổng thống Nga",
        "slug": "V_Putin tu trung ta KGB den Tong thong Nga",
        "rate": "5.0",
        "total_rate": 33,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17115.jpg?v=1&w=200&h=292",
        "author": "",
        "detailLink": "https://ebook.waka.vn/v-putin-tu-trung-ta-kgb-den-tong-thong-nga-bo3gZW.html"
    },
    {
        "id": 16973,
        "content_type": 1,
        "platform": 1,
        "title": "Như núi như mây",
        "slug": "Nhu nui nhu may",
        "rate": "5.0",
        "total_rate": 2,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16973.jpg?v=1&w=200&h=292",
        "author": "Nguyễn Đông Thức",
        "detailLink": "https://ebook.waka.vn/nhu-nui-nhu-may-b9K33W.html"
    },
    {
        "id": 16983,
        "content_type": 1,
        "platform": 1,
        "title": "Người lạ làm thay đổi cuộc sống của chúng ta",
        "slug": "Nguoi la lam thay doi cuoc song cua chung ta",
        "rate": "5.0",
        "total_rate": 9,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16983.jpg?v=2&w=200&h=292",
        "author": "Kio Stark",
        "detailLink": "https://ebook.waka.vn/nguoi-la-lam-thay-doi-cuoc-song-cua-chung-ta-bMZbmW.html"
    },
    {
        "id": 17021,
        "content_type": 1,
        "platform": 1,
        "title": "Dấu vết của mẹ",
        "slug": "Dau vet cua me",
        "rate": "5.0",
        "total_rate": 9,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/17021.jpg?v=1&w=200&h=292",
        "author": "Marta Dzido",
        "detailLink": "https://ebook.waka.vn/dau-vet-cua-me-bq2QNW.html"
    },
    {
        "id": 16994,
        "content_type": 1,
        "platform": 1,
        "title": "Báu vật của đời",
        "slug": "Bau vat cua doi",
        "rate": "5.0",
        "total_rate": 5,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16994.jpg?v=1&w=200&h=292",
        "author": "Mạc Ngôn",
        "detailLink": "https://ebook.waka.vn/bau-vat-cua-doi-bGpg1W.html"
    },
    {
        "id": 16781,
        "content_type": 1,
        "platform": 1,
        "title": "Tốc độ của niềm tin",
        "slug": "Toc do cua niem tin",
        "rate": "4.9",
        "total_rate": 45,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16781.jpg?v=1&w=200&h=292",
        "author": "Stephen R. Covey",
        "detailLink": "https://ebook.waka.vn/toc-do-cua-niem-tin-b7ExlW.html"
    },
    {
        "id": 16770,
        "content_type": 1,
        "platform": 1,
        "title": "50 tips cho những người yêu lần đầu",
        "slug": "50 tips cho nhung nguoi yeu lan dau",
        "rate": "4.9",
        "total_rate": 34,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16770.jpg?v=2&w=200&h=292",
        "author": "An Khuê",
        "detailLink": "https://ebook.waka.vn/50-tips-cho-nhung-nguoi-yeu-lan-dau-b5XxpW.html"
    },
    {
        "id": 16769,
        "content_type": 1,
        "platform": 1,
        "title": "50 tips giúp bạn vượt qua thất tình",
        "slug": "50 tips giup ban vuot qua that tinh",
        "rate": "4.9",
        "total_rate": 18,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16769.jpg?v=2&w=200&h=292",
        "author": "An Nhiên",
        "detailLink": "https://ebook.waka.vn/50-tips-giup-ban-vuot-qua-that-tinh-bmoWyW.html"
    },
    {
        "id": 16734,
        "content_type": 1,
        "platform": 1,
        "title": "Nhật ký của bố",
        "slug": "Nhat ky cua bo",
        "rate": "4.9",
        "total_rate": 42,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16734.jpg?v=1&w=200&h=292",
        "author": "Ota Toshimasa",
        "detailLink": "https://ebook.waka.vn/nhat-ky-cua-bo-bRAv5W.html"
    },
    {
        "id": 16706,
        "content_type": 1,
        "platform": 1,
        "title": "Người thông minh không làm việc một mình",
        "slug": "Nguoi thong minh khong lam viec mot minh",
        "rate": "4.6",
        "total_rate": 31,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16706.jpg?v=1&w=200&h=292",
        "author": "Rodd Wagner & Gale Muller",
        "detailLink": "https://ebook.waka.vn/nguoi-thong-minh-khong-lam-viec-mot-minh-bGpZXW.html"
    },
    {
        "id": 11993,
        "content_type": 1,
        "platform": 1,
        "title": "Yêu em cuồng si",
        "slug": "Yeu em cuong si",
        "rate": "5.0",
        "total_rate": 18,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/11993.jpg?v=2&w=200&h=292",
        "author": "Rachel Gibson",
        "detailLink": "https://ebook.waka.vn/yeu-em-cuong-si-bNx2NW.html"
    },
    {
        "id": 11703,
        "content_type": 1,
        "platform": 1,
        "title": "Đi tìm lẽ sống",
        "slug": "Di tim le song",
        "rate": "4.9",
        "total_rate": 254,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/11703.jpg?v=3&w=200&h=292",
        "author": "Viktor Emil Frankl",
        "detailLink": "https://ebook.waka.vn/di-tim-le-song-baldjW.html"
    },
    {
        "id": 11706,
        "content_type": 1,
        "platform": 1,
        "title": "Hành trình về Phương Đông",
        "slug": "Hanh trinh ve Phuong Dong",
        "rate": "4.9",
        "total_rate": 990,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/11706.jpg?v=3&w=200&h=292",
        "author": "Dr. Blair Thomas Spalding",
        "detailLink": "https://ebook.waka.vn/hanh-trinh-ve-phuong-dong-bG8nnW.html"
    },
    {
        "id": 11526,
        "content_type": 1,
        "platform": 1,
        "title": "Những ngón tay đan",
        "slug": "Nhung ngon tay dan",
        "rate": "5.0",
        "total_rate": 6,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/11526.jpg?v=4&w=200&h=292",
        "author": "Hân Như",
        "detailLink": "https://ebook.waka.vn/nhung-ngon-tay-dan-b5EoOW.html"
    },
    {
        "id": 11293,
        "content_type": 1,
        "platform": 1,
        "title": "Cuộc sống không giới hạn",
        "slug": "Cuoc song khong gioi han",
        "rate": "5.0",
        "total_rate": 60,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/11293.jpg?v=1&w=200&h=292",
        "author": "Nick Vujicic",
        "detailLink": "https://ebook.waka.vn/cuoc-song-khong-gioi-han-bNqYaW.html"
    },
    {
        "id": 10664,
        "content_type": 1,
        "platform": 1,
        "title": "Duyên kỳ ngộ (Tập 1)",
        "slug": "Duyen ky ngo (Tap 1)",
        "rate": "5.0",
        "total_rate": 28,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/10664.jpg?v=2&w=200&h=292",
        "author": "Trang Trang (Mưa Nhỏ Hồng Trần)",
        "detailLink": "https://ebook.waka.vn/duyen-ky-ngo-tap-1-bLE9vW.html"
    },
    {
        "id": 10677,
        "content_type": 1,
        "platform": 1,
        "title": "Ta muốn đến Cửu Châu",
        "slug": "Ta muon den Cuu Chau",
        "rate": "4.9",
        "total_rate": 119,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/10677.jpg?v=2&w=200&h=292",
        "author": "Cửu Lộ Phi Hương",
        "detailLink": "https://ebook.waka.vn/ta-muon-den-cuu-chau-bzDaWW.html"
    },
    {
        "id": 10428,
        "content_type": 1,
        "platform": 1,
        "title": "Tìm lại cái tôi đã mất",
        "slug": "Tim lai cai toi da mat",
        "rate": "5.0",
        "total_rate": 69,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/10428.jpg?v=3&w=200&h=292",
        "author": "Trình Chí Lương",
        "detailLink": "https://ebook.waka.vn/tim-lai-cai-toi-da-mat-bE8AjW.html"
    },
    {
        "id": 10474,
        "content_type": 1,
        "platform": 1,
        "title": "Dạy con đơn giản hiệu quả",
        "slug": "Day con don gian hieu qua",
        "rate": "5.0",
        "total_rate": 8,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/10474.jpg?v=2&w=200&h=292",
        "author": "Hoa Dương",
        "detailLink": "https://ebook.waka.vn/day-con-don-gian-hieu-qua-bxoGgW.html"
    },
    {
        "id": 9966,
        "content_type": 1,
        "platform": 1,
        "title": "Quản lý thời gian",
        "slug": "Quan ly thoi gian",
        "rate": "4.9",
        "total_rate": 148,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/9966.jpg?v=2&w=200&h=292",
        "author": "Martin Manser",
        "detailLink": "https://ebook.waka.vn/quan-ly-thoi-gian-bj60EW.html"
    },
    {
        "id": 4647,
        "content_type": 1,
        "platform": 1,
        "title": "Lời từ chối hoàn hảo",
        "slug": "Loi tu choi hoan hao",
        "rate": "4.9",
        "total_rate": 844,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/4647.jpg?v=3&w=200&h=292",
        "author": "William Ury",
        "detailLink": "https://ebook.waka.vn/loi-tu-choi-hoan-hao-ba3OGW.html"
    },
    {
        "id": 16571,
        "content_type": 1,
        "platform": 1,
        "title": "Cẩm nang tự học IELTS",
        "slug": "Cam nang tu hoc IELTS",
        "rate": "5.0",
        "total_rate": 77,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16571.jpg?v=1&w=200&h=292",
        "author": "Kiên Trần",
        "detailLink": "https://ebook.waka.vn/cam-nang-tu-hoc-ielts-bAagQW.html"
    },
    {
        "id": 14144,
        "content_type": 1,
        "platform": 1,
        "title": "Cha mẹ Pháp không đầu hàng",
        "slug": "Cha me Phap khong dau hang",
        "rate": "5.0",
        "total_rate": 5,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14144.jpg?v=2&w=200&h=292",
        "author": "Pamela Druckerman",
        "detailLink": "https://ebook.waka.vn/cha-me-phap-khong-dau-hang-bDaM7W.html"
    },
    {
        "id": 15563,
        "content_type": 1,
        "platform": 1,
        "title": "Mẹ Nhật truyền cảm hứng học cho con thế nào?",
        "slug": "Me Nhat truyen cam hung hoc cho con the nao?",
        "rate": "4.9",
        "total_rate": 37,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15563.jpg?v=1&w=200&h=292",
        "author": "Sugahara YuKo",
        "detailLink": "https://ebook.waka.vn/me-nhat-truyen-cam-hung-hoc-cho-con-the-nao-byzglW.html"
    },
    {
        "id": 16289,
        "content_type": 1,
        "platform": 1,
        "title": "Đôi cánh chức nữ",
        "slug": "Doi canh chuc nu",
        "rate": "5.0",
        "total_rate": 23,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16289.jpg?v=1&w=200&h=292",
        "author": "Đinh Hoàng Anh",
        "detailLink": "https://ebook.waka.vn/doi-canh-chuc-nu-bpd8AW.html"
    },
    {
        "id": 13895,
        "content_type": 1,
        "platform": 1,
        "title": "Đàn ông + Đàn bà = Cuộc sống",
        "slug": "Dan ong _ Dan ba = Cuoc song",
        "rate": "4.7",
        "total_rate": 23,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13895.jpg?v=2&w=200&h=292",
        "author": "Thảo Gấu",
        "detailLink": "https://ebook.waka.vn/dan-ong-dan-ba-cuoc-song-bZ44jW.html"
    },
    {
        "id": 14366,
        "content_type": 1,
        "platform": 1,
        "title": "Đứng dậy mạnh mẽ",
        "slug": "Dung day manh me",
        "rate": "5.0",
        "total_rate": 153,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14366.jpg?v=2&w=200&h=292",
        "author": "Nick Vujicic",
        "detailLink": "https://ebook.waka.vn/dung-day-manh-me-bjv5EW.html"
    },
    {
        "id": 14273,
        "content_type": 1,
        "platform": 1,
        "title": "Vô vàn xuôi ngược, vô vàn thương",
        "slug": "Vo van xuoi nguoc, vo van thuong",
        "rate": "4.8",
        "total_rate": 39,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14273.jpg?v=4&w=200&h=292",
        "author": "Gemi Phạm",
        "detailLink": "https://ebook.waka.vn/vo-van-xuoi-nguoc-vo-van-thuong-b9eW4W.html"
    },
    {
        "id": 15585,
        "content_type": 1,
        "platform": 1,
        "title": "Cách người Nhật xây dựng mối quan hệ",
        "slug": "Cach nguoi Nhat xay dung moi quan he",
        "rate": "4.9",
        "total_rate": 92,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15585.jpg?v=1&w=200&h=292",
        "author": "Kawashita Kazuhiko",
        "detailLink": "https://ebook.waka.vn/cach-nguoi-nhat-xay-dung-moi-quan-he-bXYjKW.html"
    },
    {
        "id": 16316,
        "content_type": 1,
        "platform": 1,
        "title": "Tìm lại sức mạnh tinh thần",
        "slug": "Tim lai suc manh tinh than",
        "rate": "5.0",
        "total_rate": 22,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16316.jpg?v=1&w=200&h=292",
        "author": "Jan Alcoe ",
        "detailLink": "https://ebook.waka.vn/tim-lai-suc-manh-tinh-than-bO25aW.html"
    },
    {
        "id": 13946,
        "content_type": 1,
        "platform": 1,
        "title": "400 qui tắc quản lý người và việc",
        "slug": "400 qui tac quan ly nguoi va viec",
        "rate": "4.9",
        "total_rate": 133,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13946.jpg?v=2&w=200&h=292",
        "author": "Lý Vĩ",
        "detailLink": "https://ebook.waka.vn/400-qui-tac-quan-ly-nguoi-va-viec-bYya4W.html"
    },
    {
        "id": 14465,
        "content_type": 1,
        "platform": 1,
        "title": "Độc hành - Những khám phá giá trị và kỳ lạ trên con đường tơ lụa",
        "slug": "Doc hanh - Nhung kham pha gia tri va ky la tren con duong to lua",
        "rate": "4.8",
        "total_rate": 14,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14465.jpg?v=1&w=200&h=292",
        "author": "Nguyễn Hoàng Bảo",
        "detailLink": "https://ebook.waka.vn/doc-hanh-nhung-kham-pha-gia-tri-va-ky-la-tren-con-duong-to-lua-bqd50W.html"
    },
    {
        "id": 15831,
        "content_type": 1,
        "platform": 1,
        "title": "Ba đêm định mệnh",
        "slug": "Ba dem dinh menh",
        "rate": "5.0",
        "total_rate": 6,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15831.jpg?v=1&w=200&h=292",
        "author": "Debra Mullins",
        "detailLink": "https://ebook.waka.vn/ba-dem-dinh-menh-bbwNxW.html"
    },
    {
        "id": 14334,
        "content_type": 1,
        "platform": 1,
        "title": "Săn chồng",
        "slug": "San chong",
        "rate": "4.8",
        "total_rate": 22,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14334.jpg?v=4&w=200&h=292",
        "author": "Đường Quả Mạch Tử",
        "detailLink": "https://ebook.waka.vn/san-chong-bROpQW.html"
    },
    {
        "id": 16322,
        "content_type": 1,
        "platform": 1,
        "title": "Trật tự thế giới",
        "slug": "Trat tu the gioi",
        "rate": "4.7",
        "total_rate": 55,
        "label": "",
        "price": "109.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16322.jpg?v=1&w=200&h=292",
        "author": "Henry Kissinger",
        "detailLink": "https://ebook.waka.vn/trat-tu-the-gioi-bjz5AW.html"
    },
    {
        "id": 13994,
        "content_type": 1,
        "platform": 1,
        "title": "Hà Nội Cũ Nằm Đây",
        "slug": "Ha Noi Cu Nam Day",
        "rate": "4.8",
        "total_rate": 9,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13994.jpg?v=1&w=200&h=292",
        "author": "Ngọc Giao",
        "detailLink": "https://ebook.waka.vn/ha-noi-cu-nam-day-bGG1nW.html"
    },
    {
        "id": 14637,
        "content_type": 1,
        "platform": 1,
        "title": "Em sẽ quên anh một ngày không xa",
        "slug": "Em se quen anh mot ngay khong xa",
        "rate": "5.0",
        "total_rate": 21,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14637.jpg?v=2&w=200&h=292",
        "author": "Đinh Khánh Linh",
        "detailLink": "https://ebook.waka.vn/em-se-quen-anh-mot-ngay-khong-xa-b7W5xW.html"
    },
    {
        "id": 13670,
        "content_type": 1,
        "platform": 1,
        "title": "10 phút kỳ diệu mỗi ngày thắt chặt tình cha con",
        "slug": "10 phut ky dieu moi ngay that chat tinh cha con",
        "rate": "4.8",
        "total_rate": 23,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13670.jpg?v=2&w=200&h=292",
        "author": "Shimizu Katsuhiko",
        "detailLink": "https://ebook.waka.vn/10-phut-ky-dieu-moi-ngay-that-chat-tinh-cha-con-b54wzW.html"
    },
    {
        "id": 14355,
        "content_type": 1,
        "platform": 1,
        "title": "Telesales - Tiếp thị bán hàng qua điện thoại (tái bản 2014)",
        "slug": "Telesales - Tiep thi ban hang qua dien thoai (tai ban 2014)",
        "rate": "4.9",
        "total_rate": 56,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14355.jpg?v=2&w=200&h=292",
        "author": "Bùi Xuân Phong",
        "detailLink": "https://ebook.waka.vn/telesales-tiep-thi-ban-hang-qua-dien-thoai-tai-ban-2014-b3EneW.html"
    },
    {
        "id": 16532,
        "content_type": 1,
        "platform": 1,
        "title": "Bí quyết thu phục nhân tâm",
        "slug": "Bi quyet thu phuc nhan tam",
        "rate": "4.9",
        "total_rate": 125,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16532.jpg?v=1&w=200&h=292",
        "author": "Gia Linh",
        "detailLink": "https://ebook.waka.vn/bi-quyet-thu-phuc-nhan-tam-bWpnoW.html"
    },
    {
        "id": 14075,
        "content_type": 1,
        "platform": 1,
        "title": "Đêm định mệnh - Tập 1 - Cuộc giao dịch 7 ngày",
        "slug": "Dem dinh menh - Tap 1 - Cuoc giao dich 7 ngay",
        "rate": "4.9",
        "total_rate": 135,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14075.jpg?v=3&w=200&h=292",
        "author": "Ân Tầm",
        "detailLink": "https://ebook.waka.vn/dem-dinh-menh-tap-1-cuoc-giao-dich-7-ngay-bbN9pW.html"
    },
    {
        "id": 15557,
        "content_type": 1,
        "platform": 1,
        "title": "Search inside yourself",
        "slug": "Search inside yourself",
        "rate": "4.9",
        "total_rate": 35,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15557.jpg?v=1&w=200&h=292",
        "author": "Forewords By Jon Kabat - Zinn and Daniel Goleman",
        "detailLink": "https://ebook.waka.vn/search-inside-yourself-bv8mLW.html"
    },
    {
        "id": 16280,
        "content_type": 1,
        "platform": 1,
        "title": "Tuyệt đỉnh cổ vật",
        "slug": "Tuyet dinh co vat",
        "rate": "5.0",
        "total_rate": 29,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16280.jpg?v=1&w=200&h=292",
        "author": "Nhung Hà",
        "detailLink": "https://ebook.waka.vn/tuyet-dinh-co-vat-b0nGNW.html"
    },
    {
        "id": 13862,
        "content_type": 1,
        "platform": 1,
        "title": "Bắt đầu với câu hỏi tại sao",
        "slug": "Bat dau voi cau hoi tai sao",
        "rate": "4.9",
        "total_rate": 70,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13862.jpg?v=2&w=200&h=292",
        "author": "Simon Sinek",
        "detailLink": "https://ebook.waka.vn/bat-dau-voi-cau-hoi-tai-sao-b233DW.html"
    },
    {
        "id": 14358,
        "content_type": 1,
        "platform": 1,
        "title": "Để giúp trẻ em chơi",
        "slug": "De giup tre em choi",
        "rate": "4.9",
        "total_rate": 26,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14358.jpg?v=4&w=200&h=292",
        "author": "M. R. Aufauvre Bouilly, G. Henry",
        "detailLink": "https://ebook.waka.vn/de-giup-tre-em-choi-bK2odW.html"
    },
    {
        "id": 16622,
        "content_type": 1,
        "platform": 1,
        "title": "Mỗi ngày 10 ý tưởng rèn luyện cơ bắp sáng tạo",
        "slug": "Moi ngay 10 y tuong ren luyen co bap sang tao",
        "rate": "4.9",
        "total_rate": 65,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16622.jpg?v=3&w=200&h=292",
        "author": "Claudia Azula Altucher",
        "detailLink": "https://ebook.waka.vn/moi-ngay-10-y-tuong-ren-luyen-co-bap-sang-tao-bjzlwW.html"
    },
    {
        "id": 14205,
        "content_type": 1,
        "platform": 1,
        "title": "Chúa đá Zaggla (Tập 2): Trận quyết đấu với quái vật ba chân",
        "slug": "Chua da Zaggla (Tap 2): Tran quyet dau voi quai vat ba chan",
        "rate": "4.9",
        "total_rate": 41,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14205.jpg?v=2&w=200&h=292",
        "author": "Huyền Trang",
        "detailLink": "https://ebook.waka.vn/chua-da-zaggla-tap-2-tran-quyet-dau-voi-quai-vat-ba-chan-bNOMZW.html"
    },
    {
        "id": 15567,
        "content_type": 1,
        "platform": 1,
        "title": "Quản trị thương hiệu trực tuyến",
        "slug": "Quan tri thuong hieu truc tuyen",
        "rate": "4.9",
        "total_rate": 20,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15567.jpg?v=1&w=200&h=292",
        "author": "Charlie Pownall",
        "detailLink": "https://ebook.waka.vn/quan-tri-thuong-hieu-truc-tuyen-bdG6WW.html"
    },
    {
        "id": 16299,
        "content_type": 1,
        "platform": 1,
        "title": "Thông minh hơn, nhanh hơn, giỏi hơn",
        "slug": "Thong minh hon, nhanh hon, gioi hon",
        "rate": "4.9",
        "total_rate": 353,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16299.jpg?v=2&w=200&h=292",
        "author": "Charles Duhigg",
        "detailLink": "https://ebook.waka.vn/thong-minh-hon-nhanh-hon-gioi-hon-b3onQW.html"
    },
    {
        "id": 13925,
        "content_type": 1,
        "platform": 1,
        "title": "Tôi tự hào là người Việt Nam",
        "slug": "Toi tu hao la nguoi Viet Nam",
        "rate": "4.9",
        "total_rate": 27,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13925.jpg?v=2&w=200&h=292",
        "author": "Nhiều tác giả",
        "detailLink": "https://ebook.waka.vn/toi-tu-hao-la-nguoi-viet-nam-bmOoDW.html"
    },
    {
        "id": 14376,
        "content_type": 1,
        "platform": 1,
        "title": "Trở thành thiên thần - Con đường khai sáng",
        "slug": "Tro thanh thien than - Con duong khai sang",
        "rate": "4.6",
        "total_rate": 16,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14376.jpg?v=2&w=200&h=292",
        "author": "Kaya Muller",
        "detailLink": "https://ebook.waka.vn/tro-thanh-thien-than-con-duong-khai-sang-bW7AoW.html"
    },
    {
        "id": 15693,
        "content_type": 1,
        "platform": 1,
        "title": "Những điều trường Harvard không dạy bạn",
        "slug": "Nhung dieu truong Harvard khong day ban",
        "rate": "5.0",
        "total_rate": 68,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15693.jpg?v=2&w=200&h=292",
        "author": "Mark H. McCormack",
        "detailLink": "https://ebook.waka.vn/nhung-dieu-truong-harvard-khong-day-ban-bN26aW.html"
    },
    {
        "id": 14313,
        "content_type": 1,
        "platform": 1,
        "title": "Cạm bẫy mong manh",
        "slug": "Cam bay mong manh",
        "rate": "5.0",
        "total_rate": 17,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14313.jpg?v=4&w=200&h=292",
        "author": "James Patterson, Jon Nautnon",
        "detailLink": "https://ebook.waka.vn/cam-bay-mong-manh-bv2a9W.html"
    },
    {
        "id": 16319,
        "content_type": 1,
        "platform": 1,
        "title": "Sức mạnh của sự mơ hồ và bí ẩn",
        "slug": "Suc manh cua su mo ho va bi an",
        "rate": "4.8",
        "total_rate": 80,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16319.jpg?v=1&w=200&h=292",
        "author": "Jamie Holmes",
        "detailLink": "https://ebook.waka.vn/suc-manh-cua-su-mo-ho-va-bi-an-byzZ8W.html"
    },
    {
        "id": 13955,
        "content_type": 1,
        "platform": 1,
        "title": "Phương pháp giáo dục Montessori - Phát hiện mới về trẻ thơ",
        "slug": "Phuong phap giao duc Montessori - Phat hien moi ve tre tho",
        "rate": "5.0",
        "total_rate": 36,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13955.jpg?v=2&w=200&h=292",
        "author": "Maria Montessori",
        "detailLink": "https://ebook.waka.vn/phuong-phap-giao-duc-montessori-phat-hien-moi-ve-tre-tho-b3E5EW.html"
    },
    {
        "id": 14474,
        "content_type": 1,
        "platform": 1,
        "title": "Vươn lên từ thất bại",
        "slug": "Vuon len tu that bai",
        "rate": "5.0",
        "total_rate": 58,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14474.jpg?v=2&w=200&h=292",
        "author": "Brené Brown",
        "detailLink": "https://ebook.waka.vn/vuon-len-tu-that-bai-bxR5XW.html"
    },
    {
        "id": 15876,
        "content_type": 1,
        "platform": 1,
        "title": "Tư duy đột phá",
        "slug": "Tu duy dot pha",
        "rate": "4.9",
        "total_rate": 69,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/15876.jpg?v=1&w=200&h=292",
        "author": "Hibino Shozo",
        "detailLink": "https://ebook.waka.vn/tu-duy-dot-pha-bWpp3W.html"
    },
    {
        "id": 12684,
        "content_type": 1,
        "platform": 1,
        "title": "Thân phận và hào quang",
        "slug": "Than phan va hao quang",
        "rate": "4.8",
        "total_rate": 9,
        "label": "",
        "price": "69.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/12684.jpg?v=2&w=200&h=292",
        "author": "Hoàng Nguyên Vũ",
        "detailLink": "https://ebook.waka.vn/than-phan-va-hao-quang-belNOW.html"
    },
    {
        "id": 14039,
        "content_type": 1,
        "platform": 1,
        "title": "Cô đơn cũng không khóc",
        "slug": "Co don cung khong khoc",
        "rate": "5.0",
        "total_rate": 145,
        "label": "",
        "price": "0",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14039.jpg?v=3&w=200&h=292",
        "author": "Thủy Anna",
        "detailLink": "https://ebook.waka.vn/co-don-cung-khong-khoc-bMoDVW.html"
    },
    {
        "id": 14711,
        "content_type": 1,
        "platform": 1,
        "title": "Bùi Sơ Ảnh",
        "slug": "Bui So Anh",
        "rate": "5.0",
        "total_rate": 33,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14711.jpg?v=2&w=200&h=292",
        "author": "Lục Xu",
        "detailLink": "https://ebook.waka.vn/bui-so-anh-b3EqVW.html"
    },
    {
        "id": 16155,
        "content_type": 1,
        "platform": 1,
        "title": "Văn hóa doanh nghiệp - Đỉnh cao của trí tuệ",
        "slug": "Van hoa doanh nghiep - Dinh cao cua tri tue",
        "rate": "4.9",
        "total_rate": 13,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/16155.jpg?v=1&w=200&h=292",
        "author": "TS. Đỗ Hữu Hải",
        "detailLink": "https://ebook.waka.vn/van-hoa-doanh-nghiep-dinh-cao-cua-tri-tue-b3oVEW.html"
    },
    {
        "id": 13814,
        "content_type": 1,
        "platform": 1,
        "title": "Tỷ, cho em đường sống",
        "slug": "Ty, cho em duong song",
        "rate": "4.9",
        "total_rate": 26,
        "label": "",
        "price": "45.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/13814.jpg?v=2&w=200&h=292",
        "author": "Tiểu Hài Tử Ngươi Tới Đây",
        "detailLink": "https://ebook.waka.vn/ty-cho-em-duong-song-bK2KVW.html"
    },
    {
        "id": 14357,
        "content_type": 1,
        "platform": 1,
        "title": "Thuật tổ chức hội họp",
        "slug": "Thuat to chuc hoi hop",
        "rate": "4.6",
        "total_rate": 32,
        "label": "",
        "price": "22.000",
        "thumb": "https://307a0e78.vws.vegacdn.vn/view/v2/image/img.book/0/0/0/14357.jpg?v=2&w=200&h=292",
        "author": "Brian Tracy",
        "detailLink": "https://ebook.waka.vn/thuat-to-chuc-hoi-hop-bv2w9W.html"
    }
]
const category = ['Trinh thám',"Kinh dị","Kinh tế","Ngôn tình","Văn học","Nhân vật - Sự kiện","Văn hóa - Xã hội","Khoa học - Công nghệ","Thiếu nhi","Thể loại khác"]
const content = ["https://drive.google.com/file/d/1Ieb-UYS9jcXK3TBqn4zIctWcBTEOy_gw/view", "https://drive.google.com/file/d/1gm-GezLL2cEAkP02NF17_ge9X3J0APHf/view", "https://drive.google.com/file/d/1F0S-drf8sjEMz8IlGTdr3WBP0nDlgy1l/view", "https://drive.google.com/file/d/1NxHsolHevNZ2JZKWgdAWyMGfB4IAPO10/view", "https://drive.google.com/file/d/1HNIEecVJPXHN7X1igAuSF5JAr5v6p92f/view"]
const pageNumber = [83, 158, 165, 75, 90]

const description = (tittle, author) => {
    return `Mỗi cuốn sách đều chứa đựng những thông điệp và ý nghĩa riêng mà sách muốn truyền tải đến cho người đọc. Một cuốn sách hay, phù hợp sẽ là hành trang quý giá giúp bạn thành công trên con đường mình đã trọn. Là cuốn sách nằm trong danh sách những cuốn được tìm và đọc nhiều nhất, Super Book giới thiệu đến bạn cuốn sách ${tittle} của tác giả ${author}`
}
const randomDate = (start, end) => {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}
const isVietnamese = (string) => {
    const reg = /[ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]/
    return reg.test(string)
}


const generateBook = async() => {
    try {
        let count = 0;
        let author = await User.find({userType: 'author'}).select('_id').lean();
        author = author.slice(0,5)
        console.log(author.length);
        data.forEach(async (book, index) => {
            count ++;
            const newBook = new Book({
                name: book.title,
                coverImage: book.thumb.slice(0 ,book.thumb.indexOf('?')),
                bookPoster: author[index % author.length]._id,
                category: category[index % category.length],
                description: description(book.title, book.author),
                content: content[index % content.length],
                pageNumber: pageNumber[index % pageNumber.length],
                releaseYear: randomDate(new Date(2012, 0, 1), new Date()).toISOString(),
                country: isVietnamese(book.author) ? "Việt Nam" : "Mỹ",
                author: book.author,
                publishing: true,
            })
            await newBook.save()
        })
        console.log(`Seed ${count} Book Success`);
    } catch (error) {
        throw new Error(error.message);
    }
};

module.exports = {
    generateBook
}